modLoader = "javafml"
loaderVersion = "[2,)"
license = "LGPL-3.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
